package io.github.gustavo2358.air.validation;

import io.github.gustavo2358.air.model.*;
import java.util.Objects;
import static io.github.gustavo2358.air.model.AirShape.*;

/** Bottom-up operand TypeRef resolution over exact managed occurrence/type relations. */
public final class SnapshotTypes implements AutoCloseable {
    public interface Storage extends AutoCloseable {
        void put(long operandKey,long kind,long value);long kind(long operandKey);long value(long operandKey);
        boolean beginLabels(long list);void addLabel(long list,long labelKey);boolean containsLabel(long list,long labelKey);
        AirSnapshotBuilder.Lease claim(long bytes);@Override void close();
    }
    @FunctionalInterface public interface Issues {void report(String rule,long owner,String detail);}
    public record Type(long kind,long value){public boolean present(){return kind!=0;}}
    private static final long BUILTIN=1,REFERENCE=2;
    private AirSnapshot snapshot;private SnapshotIdentityKeys keys;private SnapshotDeclarations declarations;private Storage storage;private AirSnapshotBuilder.Lease control;private boolean failed;
    public static SnapshotTypes build(AirSnapshot snapshot,SnapshotIdentityKeys keys,SnapshotDeclarations declarations,Storage storage,Issues issues){var result=new SnapshotTypes(snapshot,keys,declarations,storage);try{result.index(Objects.requireNonNull(issues));return result;}catch(RuntimeException|Error failure){result.closeSuppressed(failure);throw failure;}}
    private SnapshotTypes(AirSnapshot snapshot,SnapshotIdentityKeys keys,SnapshotDeclarations declarations,Storage storage){this.snapshot=Objects.requireNonNull(snapshot);this.keys=Objects.requireNonNull(keys);this.declarations=Objects.requireNonNull(declarations);this.storage=Objects.requireNonNull(storage);try{control=Objects.requireNonNull(storage.claim(256));}catch(RuntimeException|Error failure){closeSuppressed(failure);throw failure;}}
    private void index(Issues issues){for(long at=declarations.entities();at-->0;){long node=declarations.declaration(at,SnapshotDeclarations.Fact.NODE);if(!OPERAND.accepts(snapshot.shape(node)))continue;long id=declarations.declaration(at,SnapshotDeclarations.Fact.IDENTITY);if(declarations.fact(id,SnapshotDeclarations.Fact.NODE)!=node)continue;Type type=calculate(node,id,issues);storage.put(keys.key(id),type.kind(),type.value());}}
    private Type calculate(long node,long owner,Issues issues){return switch(snapshot.shape(node)){
        case EXPRESSIONS_LITERAL->literal(snapshot.field(node,EXPRESSIONS_LITERAL,1));
        case PLACES_OBJECT_PLACE->{long declaration=declarations.fact(snapshot.field(node,PLACES_OBJECT_PLACE,1),SnapshotDeclarations.Fact.NODE);yield declaration==0?none():fromRef(snapshot.field(declaration,MEMORY_OBJECT_DECLARATION,2));}
        case PLACES_CHOICE->fromRef(snapshot.field(node,PLACES_CHOICE,3));case PLACES_REGION_SLICE->fromRef(snapshot.field(node,PLACES_REGION_SLICE,5));case EXPRESSIONS_UNKNOWN->fromRef(snapshot.field(node,EXPRESSIONS_UNKNOWN,1));
        case EXPRESSIONS_READ->ofNode(snapshot.field(node,EXPRESSIONS_READ,1));
        case EXPRESSIONS_UNARY->unary(node,owner,issues);case EXPRESSIONS_BINARY->binary(node,owner,issues);
        case EXPRESSIONS_QUANTIZE->{expect(ofNode(snapshot.field(node,EXPRESSIONS_QUANTIZE,1)),Types.Builtin.DECIMAL,owner,issues);yield builtin(Types.Builtin.DECIMAL);}
        case EXPRESSIONS_PARSE_INTEGER->{expect(ofNode(snapshot.field(node,EXPRESSIONS_PARSE_INTEGER,1)),Types.Builtin.TEXT,owner,issues);expect(ofNode(snapshot.field(node,EXPRESSIONS_PARSE_INTEGER,2)),Types.Builtin.INT,owner,issues);yield builtin(Types.Builtin.INT);}
        case EXPRESSIONS_FORMAT_DECIMAL->{expect(ofNode(snapshot.field(node,EXPRESSIONS_FORMAT_DECIMAL,1)),Types.Builtin.DECIMAL,owner,issues);yield builtin(Types.Builtin.TEXT);}
        case EXPRESSIONS_INTEGER_DIGITS->{expect(ofNode(snapshot.field(node,EXPRESSIONS_INTEGER_DIGITS,1)),Types.Builtin.INT,owner,issues);yield builtin(Types.Builtin.TEXT);}
        case EXPRESSIONS_WRAP_INTEGER->{expect(ofNode(snapshot.field(node,EXPRESSIONS_WRAP_INTEGER,1)),Types.Builtin.INT,owner,issues);yield builtin(Types.Builtin.INT);}
        case EXPRESSIONS_FIT_DECIMAL->{expect(ofNode(snapshot.field(node,EXPRESSIONS_FIT_DECIMAL,1)),Types.Builtin.DECIMAL,owner,issues);yield builtin(Types.Builtin.DECIMAL);}
        case EXPRESSIONS_FILL_TEXT->{expect(ofNode(snapshot.field(node,EXPRESSIONS_FILL_TEXT,1)),Types.Builtin.TEXT,owner,issues);yield builtin(Types.Builtin.TEXT);}
        case EXPRESSIONS_FIT_TEXT->{expect(ofNode(snapshot.field(node,EXPRESSIONS_FIT_TEXT,1)),Types.Builtin.TEXT,owner,issues);yield builtin(Types.Builtin.TEXT);}
        case EXPRESSIONS_SLICE_TEXT->{expect(ofNode(snapshot.field(node,EXPRESSIONS_SLICE_TEXT,1)),Types.Builtin.TEXT,owner,issues);expect(ofNode(snapshot.field(node,EXPRESSIONS_SLICE_TEXT,2)),Types.Builtin.INT,owner,issues);expect(ofNode(snapshot.field(node,EXPRESSIONS_SLICE_TEXT,3)),Types.Builtin.INT,owner,issues);yield builtin(Types.Builtin.TEXT);}
        case EXPRESSIONS_TRIM_RIGHT->{expect(ofNode(snapshot.field(node,EXPRESSIONS_TRIM_RIGHT,1)),Types.Builtin.TEXT,owner,issues);yield builtin(Types.Builtin.TEXT);}
        default->throw new IllegalStateException("operand required");};}
    private Type unary(long node,long owner,Issues issues){Type argument=ofNode(snapshot.field(node,EXPRESSIONS_UNARY,2));var operator=Expressions.UnaryOperator.values()[Math.toIntExact(snapshot.scalar(snapshot.field(node,EXPRESSIONS_UNARY,1)))];return switch(operator){case NOT->{expect(argument,Types.Builtin.BOOL,owner,issues);yield builtin(Types.Builtin.BOOL);}case NEG,ABS->{numeric(argument,owner,issues);yield argument;}case TO_DECIMAL->{expect(argument,Types.Builtin.INT,owner,issues);yield builtin(Types.Builtin.DECIMAL);}case TO_INT->{expect(argument,Types.Builtin.DECIMAL,owner,issues);yield builtin(Types.Builtin.INT);}case IS_DIGITS->{expect(argument,Types.Builtin.TEXT,owner,issues);yield builtin(Types.Builtin.BOOL);}case LENGTH->{textOrBytes(argument,owner,issues);yield builtin(Types.Builtin.INT);}};}
    private Type binary(long node,long owner,Issues issues){Type left=ofNode(snapshot.field(node,EXPRESSIONS_BINARY,2)),right=ofNode(snapshot.field(node,EXPRESSIONS_BINARY,3));if(!sameKnown(left,right))issues.report("I-08",owner,"binary operator requires matching known domains, not shared unknown_type");var operator=Expressions.BinaryOperator.values()[Math.toIntExact(snapshot.scalar(snapshot.field(node,EXPRESSIONS_BINARY,1)))];return switch(operator){case EQ,NE->builtin(Types.Builtin.BOOL);case LT,LE,GT,GE->{numeric(left,owner,issues);yield builtin(Types.Builtin.BOOL);}case AND,OR->{expect(left,Types.Builtin.BOOL,owner,issues);expect(right,Types.Builtin.BOOL,owner,issues);yield builtin(Types.Builtin.BOOL);}case ADD,SUB,MUL->{numeric(left,owner,issues);numeric(right,owner,issues);yield left;}case CONCAT->{textOrBytes(left,owner,issues);textOrBytes(right,owner,issues);yield left;}};}
    private Type literal(long value){return switch(snapshot.shape(value)){case VALUES_BOOL_VALUE->builtin(Types.Builtin.BOOL);case VALUES_INT_VALUE->builtin(Types.Builtin.INT);case VALUES_DECIMAL_VALUE->builtin(Types.Builtin.DECIMAL);case VALUES_TEXT_VALUE->builtin(Types.Builtin.TEXT);case VALUES_BYTES_VALUE->builtin(Types.Builtin.BYTES);case VALUES_LABEL_VALUE->new Type(REFERENCE,snapshot.field(value,VALUES_LABEL_VALUE,1));default->throw new IllegalStateException("literal value required");};}
    public Type ofNode(long node){open();long id=snapshot.field(snapshot.field(node,snapshot.shape(node),0),OPERAND_HEADER,0);return ofId(id);}
    public Type ofId(long id){open();long key=keys.key(id);return new Type(storage.kind(key),storage.value(key));}
    public Type fromRef(long ref){return snapshot.shape(ref)==TYPES_KNOWN&&snapshot.shape(snapshot.field(ref,TYPES_KNOWN,0))==TYPES_BUILTIN?builtin(Types.Builtin.values()[Math.toIntExact(snapshot.scalar(snapshot.field(ref,TYPES_KNOWN,0)))]):new Type(REFERENCE,ref);}
    public boolean same(Type left,Type right){open();if(left.kind()!=right.kind())return false;if(left.kind()==0||left.kind()==BUILTIN)return left.value()==right.value();long a=left.value(),b=right.value();AirShape as=snapshot.shape(a),bs=snapshot.shape(b);if(as==TYPES_UNKNOWN_TYPE||bs==TYPES_UNKNOWN_TYPE)return as==bs&&keys.key(snapshot.field(a,TYPES_UNKNOWN_TYPE,0))==keys.key(snapshot.field(b,TYPES_UNKNOWN_TYPE,0));long at=as==TYPES_KNOWN?snapshot.field(a,TYPES_KNOWN,0):a,bt=bs==TYPES_KNOWN?snapshot.field(b,TYPES_KNOWN,0):b;if(snapshot.shape(at)!=snapshot.shape(bt))return false;if(snapshot.shape(at)==TYPES_BUILTIN)return snapshot.scalar(at)==snapshot.scalar(bt);if(snapshot.shape(at)==TYPES_EXTENSION_TYPE)return keys.atomKey(snapshot.field(at,TYPES_EXTENSION_TYPE,0))==keys.atomKey(snapshot.field(bt,TYPES_EXTENSION_TYPE,0))&&keys.atomKey(snapshot.field(at,TYPES_EXTENSION_TYPE,1))==keys.atomKey(snapshot.field(bt,TYPES_EXTENSION_TYPE,1));return sameLabels(at,bt);}
    public boolean sameKnown(Type a,Type b){return known(a)&&known(b)&&same(a,b);}public boolean is(Type type,Types.Builtin builtin){return type.kind()==BUILTIN&&type.value()==builtin.ordinal()+1L;}private boolean known(Type type){return type.kind()==BUILTIN||type.kind()==REFERENCE&&snapshot.shape(type.value())!=TYPES_UNKNOWN_TYPE;}
    private boolean sameLabels(long a,long b){if(keys.key(snapshot.field(a,TYPES_LABEL_TYPE,0))!=keys.key(snapshot.field(b,TYPES_LABEL_TYPE,0)))return false;long al=snapshot.field(a,TYPES_LABEL_TYPE,1),bl=snapshot.field(b,TYPES_LABEL_TYPE,1);if(snapshot.size(al)!=snapshot.size(bl))return false;indexLabels(bl);try(var rows=snapshot.elements(al,IDS_LABEL_ID)){while(rows.advance())if(!storage.containsLabel(bl,keys.key(rows.value())))return false;}return true;}
    private void indexLabels(long list){if(!storage.beginLabels(list))return;try(var rows=snapshot.elements(list,IDS_LABEL_ID)){while(rows.advance())storage.addLabel(list,keys.key(rows.value()));}}
    private void expect(Type actual,Types.Builtin expected,long owner,Issues issues){if(!is(actual,expected))issues.report("I-08",owner,"requires known("+expected+")");}private void numeric(Type type,long owner,Issues issues){if(!is(type,Types.Builtin.INT)&&!is(type,Types.Builtin.DECIMAL))issues.report("I-08",owner,"numeric operator requires known int or decimal");}private void textOrBytes(Type type,long owner,Issues issues){if(!is(type,Types.Builtin.TEXT)&&!is(type,Types.Builtin.BYTES))issues.report("I-08",owner,"operator requires known text or bytes");}
    private static Type builtin(Types.Builtin value){return new Type(BUILTIN,value.ordinal()+1L);}private static Type none(){return new Type(0,0);}
    private void open(){if(storage==null||failed)throw new IllegalStateException("snapshot types are closed or aborted");}private void closeSuppressed(Throwable failure){try{close();}catch(RuntimeException|Error cleanup){if(cleanup!=failure)failure.addSuppressed(cleanup);}}
    @Override public void close(){Storage owner=storage;storage=null;AirSnapshotBuilder.Lease lease=control;control=null;snapshot=null;keys=null;declarations=null;Throwable failure=null;try{if(owner!=null)owner.close();}catch(RuntimeException|Error cleanup){failure=cleanup;}try{if(lease!=null)lease.close();}catch(RuntimeException|Error cleanup){if(failure==null)failure=cleanup;else if(failure!=cleanup)failure.addSuppressed(cleanup);}if(failure instanceof RuntimeException error)throw error;if(failure instanceof Error error)throw error;}
}
